
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"  # Jenkins UI
      # - "50000:50000"  # Agent communication (optional)
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to control Docker
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Disable setup wizard

  playwright:
    build: .
    container_name: playwrights
    ports:
      - "3000:3000"  # Expose port if needed
    networks:
      - app-network
    env_file:
      - .env   # Your .env is in the same folder as docker-compose.yml
    # Add a DNS entry here
    dns:
      - 8.8.8.8 
      - 8.8.4.4 # or your corporate DNS server IP
   

    volumes:
      - ./:/app  # Mount everything from the current folder into /app in the container
    working_dir: /app  # The container will operate in /app
    entrypoint: ["npx", "cucumber-js"] # Run your Playwright tests by default

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
