
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"  # Jenkins UI
      # - "50000:50000"  # Agent communication (optional)
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to control Docker
      - C:/Users/YOGA X380/.ssh:/var/jenkins_home/.ssh:ro  # Mount your host SSH keys into Jenkins
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Disable setup wizard

  playwright:
    build: .
    container_name: playwrights
    # aucun bind-mount global pour ne PAS écraser node_modules
    networks:
      - app-network
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    working_dir: /app
    # la commande par défaut est définie dans le Dockerfile (CMD)

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
