global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bdd_test_metrics'
    static_configs:
      - targets: ['playwrights:8000']  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
