global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bdd_test_metrics'
    static_configs:
      - targets: ['playwright:8000']  # ✅ nom du service, PAS container_name

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
